var genres = {
	"Action and Adventure" : [
		 "Alien Invasion"
		,"Animal"
		,"Biker"
		,"Blaxploitation"
		,"Blockbusters"
		,"Buddy"
		,"Chase"
		,"Comicbook"
		,"Confined Space Action"
		,"Conspiracy Thriller"
		,"Cop Action"
		,"Costume Adventures"
		,"Desert"
		,"Disaster"
		,"Epic Adventure"
		,"Erotic Thriller"
		,"Escape"
		,"Espionage"
		,"Exploitation"
		,"Exploration"
		,"Family Adventure"
		,"Fantasy Adventure"
		,"Futuristic"
		,"Heroic Bloodshed"
		,"Historical Spectacles"
		,"Hong Kong"
		,"James Bond Series"
		,"Jungle and Safari Epics"
		,"Folktale"
		,"Martial Arts"
		,"Man or Woman in peril"
		,"Man vs. Nature"
		,"Mountain"
		,"Odd couple"
		,"Period Action"
		,"Political Conspiracy"
		,"Prison"
		,"Psychological Thriller"
		,"Quest"
		,"Road trip"
		,"Romantic Adventures"
		,"Sci-Fi Action/Adventure"
		,"Samurai"
		,"Sea Adventures"
		,"Space Adventures"
		,"Sports"
		,"Spy"
		,"Superhero"
		,"Surfing"
		,"Survival"
		,"Swashbuckler"
		,"Sword and Sandal"
		,"Sword and Sorcery"
		,"Suspense-Thriller"
		,"Techno-Thriller"
		,"Treasure Hunt"
		,"Undercover"
		,"Video Game"
	]
	,"Crime" : [
		 "Bad Girl"
		,"Buddy Cop"
		,"Heist"
		,"Caper"
		,"Cops & Robbers"
		,"Courtroom"
		,"Crime Comedy or"
		,"Detective Mystery"
		,"Espionage"
		,"Femme Fatales"
		,"Film Noir"
		,"Gangs"
		,"Hard-boiled Detective"
		,"Heist"
		,"Hood"
		,"Juvenile Delinquency"
		,"Law and Order"
		,"Lovers on the Run Road"
		,"Gangster"
		,"Mystery"
		,"Neo-Noir"
		,"Outlaw Biker"
		,"Post-Noir"
		,"Procedurals"
		,"Prison"
		,"Private-Eye"
		,"Suspense-Thriller"
		,"Trial"
		,"True Crime"
		,"Vice"
		,"Victim"
		,"Who-dun-its"
		,"Women in Prison"
	]
	,"Comedy" : [
		 "Absurd"
		,"Action"
		,"Anarchic"
		,"Animals"
		,"Dark Humor"
		,"British Humor"
		,"Buddy"
		,"Classic"
		,"Clown"
		,"Comedy Thrillers"
		,"Comic Criminals"
		,"Coming of Age"
		,"Conceptual"
		,"Crime/Caper"
		,"Dumb"
		,"Fairy Tale"
		,"Family"
		,"Farce"
		,"Fish-out-of-water"
		,"Gross-out"
		,"Horror"
		,"Lampoon"
		,"Mafia"
		,"Meet-Cute Screwball or Romantic"
		,"Military"
		,"Mock-umentary (Fake Documentary)"
		,"Musical"
		,"Parenthood"
		,"Parody"
		,"Political"
		,"Populist"
		,"Pre-Teen"
		,"Re-Marriage"
		,"Road Trip"
		,"Romantic"
		,"Satire"
		,"School Days"
		,"Screwball"
		,"Sex"
		,"Slacker"
		,"Slapstick"
		,"Social-Class"
		,"Sophisticated"
		,"Spoofs"
		,"Sports"
		,"Stand-Up"
		,"Stoner"
		,"Supernatural"
		,"Teen/Teen Sex"
		,"Urban"
		,"War"
		,"Western"
		,"Zombie"
	]
	,"Drama" : [
		 "Adaptation"
		,"Addiction"
		,"Adventure"
		,"Adult"
		,"African-American"
		,"Americana"
		,"Biography"
		,"Based on a True Story"
		,"Biographical"
		,"British Empire"
		,"Buddy"
		,"Chick Flick"
		,"Childhood"
		,"Christmas"
		,"Coming-of-Age"
		,"Dance"
		,"Diary"
		,"Disease or Disability"
		,"Disaster"
		,"Docu-drama"
		,"Ensemble"
		,"Erotic"
		,"Espionage"
		,"Ethnic Family Saga"
		,"Euro-Spy"
		,"Fallen Woman"
		,"Fantasy"
		,"Feminist"
		,"Gay and Lesbian"
		,"Guy Cry"
		,"Generation Gap"
		,"Religious Figure"
		,"Heavenly"
		,"High School"
		,"Holiday"
		,"Holocaust"
		,"Hood"
		,"Inspirational"
		,"Investigative Reporting"
		,"Legal or Courtroom"
		,"Life Story"
		,"Literary Adaptation"
		,"Love"
		,"Marital"
		,"Medical"
		,"Message Movie"
		,"Musical"
		,"Newspaper"
		,"Nostalgia"
		,"Odd Couple"
		,"Period"
		,"Police"
		,"Prisoner of War"
		,"Presidential"
		,"Prison"
		,"Propaganda"
		,"Prostitution"
		,"Psychological"
		,"Race Relations"
		,"Religious"
		,"Resistance"
		,"Reunion"
		,"Road Movie"
		,"Romantic"
		,"Rural"
		,"Shakespearean"
		,"Showbiz"
		,"Slice of Life"
		,"Soap Opera"
		,"Social Commentary"
		,"Small-town Life"
		,"Sports"
		,"Supernatural"
		,"Tearjerker"
		,"Teen (or Youth)"
		,"Tragedy"
		,"True Crime"
		,"Urban"
		,"War-Military"
		,"Women's Friendship"
		,"Youth Culture"
	]
	,"Science Fiction and Fantasy" : [
		 "Action or Adventure Sci-Fi"
		,"Alien Invasion"
		,"Aliens, Extra-Terrestrial Encounters"
		,"Anime"
		,"AI (Artificial Intelligence)"
		,"Atomic Age"
		,"Classic Sci-Fi"
		,"Creature Films"
		,"Dystopia"
		,"End of the World"
		,"Exploration"
		,"Fairy Tales"
		,"Fantasy Films"
		,"50's Sci-Fi"
		,"First Contact"
		,"Futuristic"
		,"Galactic Empire"
		,"Lost Worlds"
		,"Mad Scientists"
		,"Militaristic"
		,"Monsters and Mutants"
		,"Mythic Fables or Mythology"
		,"Natural Horror"
		,"Near Future"
		,"Other Dimensions"
		,"Outer Space"
		,"Parallel Reality"
		,"Post-Apocalyptic"
		,"Pre-historic"
		,"Psychological Sci-Fi"
		,"Pulp"
		,"Cyber Punk"
		,"Steam Punk"
		,"Religious"
		,"Robots, Cyborgs and Androids"
		,"Sci-Fi Comedies"
		,"Sci-Fi Horror"
		,"Sci-Fi Thrillers"
		,"Space Opera"
		,"Space or Sci-Fi Westerns"
		,"Speculative"
		,"Star Trek"
		,"Superhero"
		,"Supernatural"
		,"Tech-Noir"
		,"Time or Space Travel"
		,"Virtual Reality"
	]
	,"Musical and Dance" : [
		 "Animated"
		,"Backstage"
		,"Ballet"
		,"Beach Party Films"
		,"Musical Biographies"
		,"Broadway Show"
		,"Comedy"
		,"Concert Films"
		,"Dance Films"
		,"Dramatic"
		,"Fairy-tale"
		,"Fantasy Musical"
		,"Film-Opera"
		,"Folk"
		,"Hip-Hop Films"
		,"Operettas"
		,"Rock-umentary"
		,"Romantic"
		,"Show-Biz Comedy"
		,"Stage"
		,"Western"
	]
	,"Horror" : [
		 "B-Movie"
		,"Cannibal"
		,"Classic"
		,"Costume"
		,"Creature Features"
		,"Demonic"
		,"Dracula"
		,"Erotic"
		,"Found Footage"
		,"Mad Scientist"
		,"Ghost"
		,"Gore"
		,"Gothic"
		,"Haunted"
		,"Halloween"
		,"Horror Comedy"
		,"H.P. Lovecraftian"
		,"Macabre"
		,"Man-Mades"
		,"Monsters"
		,"Natural"
		,"Occult"
		,"Paranormal"
		,"Post-Apocalyptic"
		,"Psychic Powers"
		,"Psychological"
		,"Reincarnation"
		,"Sadistic"
		,"Sci-Fi"
		,"Serial Killer"
		,"Sex"
		,"Slasher"
		,"Supernatural"
		,"Survival"
		,"Teen Scream"
		,"Terror"
		,"Vampires"
		,"Witchcraft"
		,"Werewolf"
		,"Zombies"
	]
	,"History" : [
		 "Alternate History"
		,"Biblical"
		,"British Empire"
		,"Dark Ages"
		,"Greek Myth"
		,"Epic Biography"
		,"Indian History"
		,"Literary Adaptation"
		,"Medieval (Dark Ages)"
		,"Period Piece"
		,"Religious"
		,"Roman Empire"
		,"Romantic Epic"
		,"Sword and Sandal"
		,"War History"
		,"Western History"
	]
	,"Western" : [
		 "Animal"
		,"B-Western"
		,"Biographies"
		,"Cattle Drive"
		,"Cavalry"
		,"Comedy"
		,"Epic"
		,"Euro-Westerns"
		,"Frontier"
		,"Gunfighters"
		,"Historical"
		,"Horror"
		,"Issue"
		,"Marshal"
		,"Martial Arts"
		,"Military"
		,"Modern"
		,"Musical"
		,"Native American"
		,"Outlaws"
		,"Psychological"
		,"Revenge"
		,"Revisionist"
		,"Road-Trail Journeys"
		,"Romantic"
		,"Science-Fiction"
		,"Shoot-outs"
		,"Space"
		,"Spaghetti"
		,"Spoof"
		,"Traditional"
	]
	,"War" : [
		 "Aviation"
		,"Afghanistan-Iraq Conflict"
		,"Anti-War"
		,"Civil War"
		,"Combat"
		,"Escape"
		,"Gulf War"
		,"Historical"
		,"Korean War"
		,"Military"
		,"Military Comedy"
		,"Propaganda"
		,"Resistance"
		,"Revolutionary War"
		,"War-Spy"
		,"Submarine"
		,"Vietnam War"
		,"War Adventure"
		,"War Epic"
		,"War Romance"
		,"World War I"
		,"World War II"
		,"World War III"
	]
}

