var tropes = [
	 "15 Minutes of Fame" 
	,"Accidental Athlete" 
	,"Accidental Hero" 
	,"Accidental Marriage" 
	,"Action Hero Babysitter" 
	,"Adventures in the Bible" 
	,"All for Nothing" 
	,"All That Glitters" 
	,"All Up to You" 
	,"All Your Base Are Belong to Us" 
	,"Alien Invasion" 
	,"Allegory Adventure" 
	,"Alternate Universe" 
	,"America Saves the Day" 
	,"Amnesia Danger" 
	,"And Now You Must Marry Me" 
	,"Animal Athlete Loophole" 
	,"Animal Testing" 
	,"Annoying Patient" 
	,"Antagonist in Mourning" 
	,"Anticlimactic Parent" 
	,"Appease the Volcano God" 
	,"April Fools' Plot" 
	,"Assimilation Plot" 
	,"Attack of the Town Festival" 
	,"Axes at School" 
	,"The B Grade" 
	,"Bachelor Auction" 
	,"Back to School" 
	,"Bad Luck Charm" 
	,"Bad Samaritan" 
	,"Bad Santa" 
	,"Badass in Distress" 
	,"Shakespeare Plot" 
	,"I've got Batman in My Basement" 
	,"Be Careful What You Wish For" 
	,"Be Yourself" 
	,"Beauty Contest" 
	,"Becoming the Costume" 
	,"Becoming the Mask" 
	,"Benched Hero" 
	,"The Big Race" 
	,"Just want to dance" 
	,"Bizarro Episode" 
	,"Black Like Me" 
	,"Body-Count Competition" 
	,"Body Horror" 
	,"Body Snatcher" 
	,"Body Surf" 
	,"Bottle Episode" 
	,"Brainwashed" 
	,"The Bride With A Past" 
	,"Bring Help Back" 
	,"Bring It Back Alive" 
	,"Bring News Back" 
	,"Broken Pedestal" 
	,"Broken Streak" 
	,"Broken Treasure" 
	,"Brought Down to Badass" 
	,"Brought Down to Normal" 
	,"Bruce Wayne Held Hostage" 
	,"Business as Unusual" 
	,"Busman's Holiday" 
	,"But I Can't Be Pregnant!" 
	,"Cabin Fever" 
	,"Cain and Abel" 
	,"The Cake Is a Lie" 
	,"Can't Get In Trouble For Nuthin'" 
	,"Caper Rationalization" 
	,"The Captivity Narrative" 
	,"Captured Super-Entity" 
	,"Celebrity Is Overrated" 
	,"Celebrity Lie" 
	,"Celebrity Star" 
	,"Chain of Deals" 
	,"The Chain of Harm" 
	,"Changing of the Guard" 
	,"Character Focus" 
	,"Charlie and the Chocolate Parody" 
	,"The Chase" 
	,"Chased by Angry Natives" 
	,"Childhood Memory Demolition Team" 
	,"Children Raise You" 
	,"Cinderella Circumstances" 
	,"City in a Bottle" 
	,"Class Reunion" 
	,"Clean Up The Town" 
	,"Clear My Name" 
	,"Clear Their Name" 
	,"Clip Show" 
	,"Closed Circle" 
	,"Code Silver" 
	,"Cold Equation" 
	,"The Collector" 
	,"Color Me Black" 
	,"Comic Books Are Real" 
	,"Coming-Out Story" 
	,"Have You Tried Not Being a Monster?" 
	,"Common Nonsense Jury" 
	,"Community-Threatening Construction" 
	,"Compromising Memoirs" 
	,"The Con" 
	,"Consolation World Record" 
	,"Contagious Powers" 
	,"Contract on the Hitman" 
	,"The Convenient Store Next Door" 
	,"Cooking Duel" 
	,"Cooperation Gambit" 
	,"Cosmetic Catastrophe" 
	,"Costumer" 
	,"Counter Zany" 
	,"Courtroom Episode" 
	,"Crapsack World" 
	,"Crash Course Landing" 
	,"Credit Card Plot" 
	,"Criminal Mind Games" 
	,"Crossing the Desert" 
	,"Crouching Moron, Hidden Badass" 
	,"Crying Wolf" 
	,"Cuckoo Nest" 
	,"Cultural Personality Makeover" 
	,"Cutting the Knot" 
	,"Dangerous Device Disposal Debacle" 
	,"Date Peepers" 
	,"Day in the Life" 
	,"A Day in the Limelight" 
	,"The Day of Reckoning" 
	,"Dead Alternate Counterpart" 
	,"Dead Pet Sketch" 
	,"Deadly Game" 
	,"Deadly Graduation" 
	,"Deadly Road Trip" 
	,"Deadly Upgrade" 
	,"Deal with the Devil" 
	,"Death in the Clouds" 
	,"Death Is a Sad Thing" 
	,"Death Takes a Holiday" 
	,"De-Power" 
	,"Defector from Commie Land" 
	,"Descent into Addiction" 
	,"Deserted Island" 
	,"Despite the Plan" 
	,"Destructive Saviour" 
	,"Deus Exit Machina" 
	,"Die Hard on an X" 
	,"Digging to China" 
	,"Digital Piracy Is Evil" 
	,"Dinner with the Boss" 
	,"Disability as an Excuse for Jerkassery" 
	,"Divide and Conquer" 
	,"Divided We Fall" 
	,"Do They Know It's Christmas Time?" 
	,"The Documentary" 
	,"A Dog Ate My Homework" 
	,"Don't Celebrate Just Yet" 
	,"Don't Go in the Woods" 
	,"Doomed Moral Victor" 
	,"Doorstop Baby" 
	,"Dork Horse Candidate" 
	,"Down the Rabbit Hole" 
	,"The Dragons Come Back" 
	,"Driving Question" 
	,"Driving Test" 
	,"Duel to the Death" 
	,"Duels Decide Everything" 
	,"Dug in Deeper" 
	,"Easily Thwarted Alien Invasion" 
	,"Easter Bunny" 
	,"Egg Sitting" 
	,"Election Day Episode" 
	,"Elseworld" 
	,"Embarrassing Rescue" 
	,"Emergency Impersonation" 
	,"Emergency Refuelling" 
	,"Empire with a Dark Secret" 
	,"Empty Quiver" 
	,"End of an Age" 
	,"Endurance Duel" 
	,"Enemy Mine" 
	,"The Epic" 
	,"Epic Race" 
	,"Epiphanic Prison" 
	,"Equivalent Exchange" 
	,"Escape from the Crazy Place" 
	,"Everybody Must Get Stoned" 
	,"Everybody's Dead, Dave" 
	,"Everyone Meets Everyone" 
	,"Everything but the Girl" 
	,"Evil Plan" 
	,"Eviler Than Thou" 
	,"Evil Twin" 
	,"Evil Will Fail" 
	,"The Evils of Free Will" 
	,"Exact Words" 
	,"Experimental Archeology" 
	,"Extreme Sport Excuse Plot" 
	,"Failed Audition Plot" 
	,"Fairest of Them All" 
	,"Fairy Tale Episode" 
	,"Faked Rip Van Winkle" 
	,"False Crucible" 
	,"False Utopia" 
	,"Family Disunion" 
	,"Fantastic Voyage" 
	,"Faustian Rebellion" 
	,"Fauxtastic Voyage" 
	,"Favouritism Flip Flop" 
	,"Fawlty Towers Plot" 
	,"Fidelity Test" 
	,"Field Trip to the Past" 
	,"Fight Clubbing" 
	,"Fight to Survive" 
	,"Fight Dracula" 
	,"Fighting for a Homeland" 
	,"The Final Temptation" 
	,"Finding Judas" 
	,"Find the Cure" 
	,"Fish Out of Temporal Water" 
	,"Flatline Plotline" 
	,"Flower from the Mountaintop" 
	,"False Cure" 
	,"A Fool and His New Money Are Soon Parted" 
	,"For Science!" 
	,"For Want of a Nail" 
	,"Forced Out of the Closet" 
	,"Foreign Correspondent" 
	,"Forgiveness Requires Death" 
	,"Forgot the Call" 
	,"Forgotten Anniversary" 
	,"Fourth Wall Shut In Story" 
	,"Free the Frogs" 
	,"Frequently-Broken Unbreakable Vow" 
	,"A Friend in Need" 
	,"Frivolous Lawsuit" 
	,"From Beyond the Fourth Wall" 
	,"From Nobody to Nightmare" 
	,"Fully Absorbed Finale" 
	,"Fumbling the Gauntlet" 
	,"The Fun in Funeral" 
	,"Fundraiser Carnival" 
	,"Gambit Roulette" 
	,"The Game Never Stopped" 
	,"The Game Plays You" 
	,"Game Show Appearance" 
	,"Garage Band" 
	,"Garage Sale" 
	,"Generational Saga" 
	,"Genocide Backfire" 
	,"Get Back to the Future" 
	,"Ghost Ship" 
	,"Ghost Story" 
	,"Girls Behind Bars" 
	,"Giving Radio to the Romans" 
	,"Gladiator Revolt" 
	,"Go Among Mad People" 
	,"God and Satan Are Both Jerks" 
	,"God for a Day" 
	,"Going Native" 
	,"Going to See the Elephant" 
	,"Gold Fever" 
	,"Gondor Calls for Aid" 
	,"Gotta Have It Gonna Steal It" 
	,"Government Conspiracy" 
	,"Grand Finale" 
	,"Grand Theft Me" 
	,"Grass Is Greener" 
	,"Great Escape" 
	,"The Great Repair" 
	,"The Greatest Story Never Told" 
	,"Groundhog Day Loop" 
	,"Guarding The Portal" 
	,"Guess Who I'm Marrying?" 
	,"Gym Class Rope Climb" 
	,"Halfway Plot Switch" 
	,"Handcuffed Briefcase" 
	,"Happy Ending Massage" 
	,"Harbinger of Impending Doom" 
	,"He Knows Too Much" 
	,"Headbutting Heroes" 
	,"Hell Invades Heaven" 
	,"Hell on Earth" 
	,"Her Code Name Was Mary Sue" 
	,"Hero For A Day" 
	,"Hero on Hiatus" 
	,"Heroes Gone Fishing" 
	,"Heroic Rematch" 
	,"Hero's Evil Predecessor Plot" 
	,"Hiccup Hijinks" 
	,"Hired to Hunt Yourself" 
	,"The Hollywood Formula" 
	,"The Homeward Journey" 
	,"Horrible Camping Trip" 
	,"Hot for Student" 
	,"Hourglass Plot" 
	,"House Inspection" 
	,"Humanity on Trial" 
	,"Hyde And Seek" 
	,"Hyperlink Story" 
	,"Hypno Fool" 
	,"I Am Who?" 
	,"I Will Find You" 
	,"I Wish It Were Real" 
	,"Identity Impersonator" 
	,"Impossible Mission" 
	,"In Another Man's Shoes" 
	,"In Defence Of Story Telling" 
	,"In with the In Crowd" 
	,"Inadequate Inheritor" 
	,"Indy Ploy" 
	,"Inept Aptitude Test" 
	,"The Infiltration" 
	,"Innocence Lost" 
	,"Innocent Bystander Series" 
	,"The Inspector Is Coming" 
	,"Inside a Computer System" 
	,"Instant Book Deal" 
	,"Intergenerational Friendship" 
	,"Interrupted Cooldown Hug" 
	,"Intoxication Ensues" 
	,"Intrepid Fictioneer" 
	,"Invented Individual" 
	,"Invisible Main Character" 
	,"Involuntary Charity Donation" 
	,"Irritation Is the Sincerest Form of Flattery" 
	,"It's a Costume Party, I Swear" 
	,"It's a Wonderful Plot" 
	,"It's Personal" 
	,"Jackie Robinson Story" 
	,"Jailbird of Panama" 
	,"Japanese Spirit" 
	,"Shark Attack" 
	,"Jekyll & Hyde" 
	,"Jigsaw Puzzle Plot" 
	,"Joker Jury" 
	,"Journey to the Center of the Mind" 
	,"Judgment of Solomon" 
	,"Jumping Off the Slippery Slope" 
	,"The Jungle Opera" 
	,"Jury of the Damned" 
	,"Just Fine Without You" 
	,"Fancifully incorrect hypothesis" 
	,"Just Think of the Potential" 
	,"Kafka Komedy" 
	,"Kangaroo Court" 
	,"Kansas City Shuffle" 
	,"Keystone Army" 
	,"Kids Versus Adults" 
	,"Kill Me Now or Forever Stay Your Hand" 
	,"Killed to Uphold the Masquerade" 
	,"Killing for a Tissue Sample" 
	,"Kingmaker Scenario" 
	,"Kudzu Plot" 
	,"Last Fertile Region" 
	,"Late to the Tragedy" 
	,"Leave Your Quest Test" 
	,"Legion of Doom" 
	,"Like a Duck Takes to Water" 
	,"Like You Were Dying" 
	,"Live-Action Escort Mission" 
	,"Loan Shark" 
	,"Locked Room Mystery" 
	,"Lonely at the Top" 
	,"Long Game" 
	,"Lost Orphaned Royalty" 
	,"Lost Wedding Ring" 
	,"Lottery of Doom" 
	,"Lotus-Eater Machine" 
	,"Love Triangle" 
	,"Lower Deck Episode" 
	,"MacGuffin Escort Mission" 
	,"Macho Disaster Expedition" 
	,"Madden Into Misanthropy" 
	,"Made a Slave" 
	,"The Magic Comes Back" 
	,"The Magic Goes Away" 
	,"The Magnificent Seven Samurai" 
	,"Mail-Order Bride" 
	,"Maintain the Lie" 
	,"Make Room For The New Plot" 
	,"Make the Bear Angry Again" 
	,"Make Up or Break Up" 
	,"The Makeover" 
	,"Making The Masterpiece" 
	,"Malignant Plot Tumor" 
	,"Mall Santa" 
	,"Man in the Iron Mask" 
	,"Man Versus Machine" 
	,"Mandatory Unretirement" 
	,"Manufacturing Victims" 
	,"Masquerade Ball" 
	,"May the Farce Be with You" 
	,"Meet Your Early Installment Weirdness" 
	,"Mental Story" 
	,"Me's a Crowd" 
	,"The Migration" 
	,"Minor Crime Reveals Major Plot" 
	,"Miss Conception" 
	,"Missing Steps Plan" 
	,"Mission from God" 
	,"Moby Schtick" 
	,"Mock Guffin" 
	,"Monster Is a Mommy" 
	,"Monster Protection Racket" 
	,"More Than Mind Control" 
	,"Movie-Making Mess" 
	,"The Moving Experience" 
	,"Moving the Goalposts" 
	,"Mundanization" 
	,"Musical Episode" 
	,"My Biological Clock Is Ticking" 
	,"My Death Is Just the Beginning" 
	,"Nasty Party" 
	,"Never Learned to Read" 
	,"Never Lend to a Friend" 
	,"Never Win the Lottery" 
	,"New Ability Addiction" 
	,"New Powers as the Plot Demands" 
	,"New Super Power" 
	,"Nitro Express" 
	,"No Antagonist" 
	,"No Doubt The Years Have Changed Me" 
	,"No Guy Wants an Amazon" 
	,"No Plot? No Problem!" 
	,"No Sympathy" 
	,"Noah's Story Arc" 
	,"Noir Episode" 
	,"Non-Protagonist Resolver" 
	,"Not Himself" 
	,"Not Just a Tournament" 
	,"Not-So-Forgotten Birthday" 
	,"Not-So-Imaginary Friend" 
	,"Oddly Common Rarity" 
	,"Off the Wagon" 
	,"An Offer You Can't Refuse" 
	,"Older Hero vs. Younger Villain" 
	,"On the Money" 
	,"One of Our Own" 
	,"One Born Every Minute" 
	,"One We Prepared Earlier" 
	,"The One Who Made It Out" 
	,"The Only One" 
	,"Out-of-Genre Experience" 
	,"Paranormal Episode" 
	,"Parent Trap Plot" 
	,"Parents for a Day" 
	,"Parody Episode" 
	,"Passed-Over Inheritance" 
	,"Passed-Over Promotion" 
	,"Passion Play" 
	,"Passing the Torch" 
	,"Peer Pressure Makes You Evil" 
	,"Penny Among Diamonds" 
	,"People Zoo" 
	,"Pet Baby Wild Animal" 
	,"Pick Up Babes With Babes" 
	,"Picture Day" 
	,"Pirate Booty" 
	,"Plague of Good Fortune" 
	,"Playing Both Sides" 
	,"Playing Cyrano" 
	,"Playing Sick" 
	,"Plot Detour" 
	,"Plot Driving Secret" 
	,"Plot Immunity" 
	,"Plot Leveling" 
	,"Plot Line Crossover" 
	,"Plot Tailored to the Party" 
	,"Poison-and-Cure Gambit" 
	,"Police Brutality Gambit" 
	,"Pony Tale" 
	,"Poorly Disguised Pilot" 
	,"Porn Without Plot" 
	,"Porn with Plot" 
	,"Portal Book" 
	,"Possessive Paradise" 
	,"Post Robbery Trauma" 
	,"Predatory Business" 
	,"Premature Empowerment" 
	,"Premiere" 
	,"Prevent the War" 
	,"Pride Before a Fall" 
	,"Prince and Pauper" 
	,"Princess for a Day" 
	,"Prodigal Family" 
	,"Prodigal Hero" 
	,"The Promised Land" 
	,"Property Line" 
	,"Protagonist Journey to Villain" 
	,"Protect This House" 
	,"Pursuing Parental Perils" 
	,"Push Polling" 
	,"Putting the Band Back Together" 
	,"Pygmalion Plot" 
	,"Pygmalion Snap Back" 
	,"The Quest" 
	,"Quest for a Wish" 
	,"Quest for Identity" 
	,"Quest for the Rest" 
	,"Race Against the Clock" 
	,"Radio Contest" 
	,"Radish Cure" 
	,"Rage Against the Heavens" 
	,"Rage Within The Machine" 
	,"Rags to Royalty" 
	,"Railroad Plot" 
	,"Rampage from a Nail" 
	,"Random Events Plot" 
	,"Ransacked Room" 
	,"Reactionary Fantasy" 
	,"Read the Fine Print" 
	,"Reading Is Cool Aesop" 
	,"A Real Man Is a Killer" 
	,"Real World Episode" 
	,"Really Seventeen Years Old" 
	,"Rear Window Investigation" 
	,"Rear Window Witness" 
	,"Reassignment Backfire" 
	,"Rebuilt Pedestal" 
	,"Redemption Quest" 
	,"Reluctant Retiree" 
	,"Rescue Arc" 
	,"Rescued from the Underworld" 
	,"Restart the World" 
	,"Revealing Cover-Up" 
	,"Revenge of the Nerd" 
	,"Rightful King Returns" 
	,"Rip Van Winkle" 
	,"Rise of Zitboy" 
	,"River of Insanity" 
	,"Road Trip Romance" 
	,"Roaring Rampage of Rescue" 
	,"Roaring Rampage of Revenge" 
	,"Robbing the Mob Bank" 
	,"Robinsonade" 
	,"Rogue Juror" 
	,"Run for the Border" 
	,"Safety Worst" 
	,"Satchel Switcheroo" 
	,"Save Our Students" 
	,"Save Your Deity" 
	,"Saving Christmas" 
	,"Saving the Orphanage" 
	,"Scare Dare" 
	,"Scarecrow Solution" 
	,"Scarpia Ultimatum" 
	,"Scary Surprise Party" 
	,"Scavenger Hunt" 
	,"School for Scheming" 
	,"Schrödinger's Butterfly" 
	,"Science Is Useless" 
	,"Scooby-Doo Hoax" 
	,"Screw the Rules, I'm Doing What's Right" 
	,"Season Finale" 
	,"Secret Diary" 
	,"Secret Relationship" 
	,"Selective Enforcement" 
	,"Send in the Search Team" 
	,"Separated at Birth" 
	,"Serial Killer" 
	,"Settling the Frontier" 
	,"Sex as Rite-of-Passage" 
	,"Sex Equals Love" 
	,"Sex for Services" 
	,"Sexy Man, Instant Harem" 
	,"Shaggy Dog Story" 
	,"Shapeshifting" 
	,"The Show Must Go On" 
	,"Show Within a Show" 
	,"Sidekick Glass Ceiling" 
	,"The Siege" 
	,"A Simple Plan" 
	,"One Crazy Night" 
	,"Sink-or-Swim Fatherhood" 
	,"Sinking Ship Scenario" 
	,"Sleep Learning" 
	,"Snipe Hunt" 
	,"Snowed-In" 
	,"The So-Called Coward" 
	,"So Near Yet So Far" 
	,"Sorcerer's Apprentice" 
	,"Souvenir Land" 
	,"Speed Dating" 
	,"Spelling Bee" 
	,"Split And Reunion" 
	,"Spot the Imposter" 
	,"Start My Own" 
	,"Start of Darkness" 
	,"Stone Soup" 
	,"Storybook Episode" 
	,"Stranger in a Strange School" 
	,"Strangers on a Train Murder" 
	,"Stumbling Upon the Lost Wizard" 
	,"Subverted Suspicion Aesop" 
	,"Succession Crisis" 
	,"Sudden Intelligence" 
	,"Suicide Mission" 
	,"Summon Everyman Hero" 
	,"Super Powers for a Day" 
	,"Superhero Episode" 
	,"Superhero Origin" 
	,"Tag-Along Actor" 
	,"Tag Team Suicide" 
	,"Taking Over the Town" 
	,"Talent Contest" 
	,"Talking Your Way Out" 
	,"Tall Tale" 
	,"The Taxi" 
	,"Teach Him Anger" 
	,"Technician vs. Performer" 
	,"Ten Little Murder Victims" 
	,"Their First Time" 
	,"There's No Place Like Home" 
	,"Thriller on the Express" 
	,"Through the Eyes of Madness" 
	,"Time to Move" 
	,"Time Travel Escape" 
	,"Time Travel Romance" 
	,"To Hell and Back" 
	,"Tontine" 
	,"Too Many Cooks Spoil the Soup" 
	,"Too Smart for Strangers" 
	,"Tournament Arc" 
	,"Train Job" 
	,"Training Accident" 
	,"Training the Peaceful Villagers" 
	,"Trapped in the Past" 
	,"Trapped in TV Land" 
	,"Trapped with Monster Plot" 
	,"Treasure Map" 
	,"Trend Aesop" 
	,"Tricked Into Signing" 
	,"Trouble Follows You Home" 
	,"Trouble from the Past" 
	,"Troublemaking New Pet" 
	,"A True Story In My Universe" 
	,"Truman Show Plot" 
	,"Turned Against Their Masters" 
	,"Turn in Your Badge" 
	,"Twelfth Night Adventure" 
	,"Twin Switch" 
	,"Two-Timer Date" 
	,"Unbelievable Source Plot" 
	,"Undercover as Lovers" 
	,"Unlocking the Talent" 
	,"Unsettling Gender Reveal" 
	,"Untrusting Community" 
	,"Unwanted Gift Plot" 
	,"Unwanted Glasses Plot" 
	,"Unwanted Rescue" 
	,"Unwanted Revival" 
	,"Unwitting Test Subject" 
	,"Utopia Justifies the Means" 
	,"Vampire Refugee" 
	,"Vanishing Village" 
	,"Very Special Episode" 
	,"Vignette Episode" 
	,"Villain-Beating Artifact" 
	,"Villain Perspective" 
	,"Visions of Another Self" 
	,"Visit by Divorced Dad" 
	,"Wake Up, Go to School, Save the World" 
	,"War for Fun and Profit" 
	,"Was Too Hard on Him" 
	,"Wayback Trip" 
	,"Wedding Day" 
	,"We Need to Get Proof" 
	,"We Want Our Jerk Back" 
	,"We Would Have Told You, But..." 
	,"Well-Intentioned Replacement" 
	,"What Could Possibly Go Wrong?" 
	,"Who Will Take the Kids?" 
	,"Whodunnit to Me" 
	,"Whole Episode Flashback" 
	,"Whole Plot Reference" 
	,"Witch Hunt" 
	,"Working the Same Case" 
	,"World Limited to the Plot" 
	,"World Tour" 
	,"Wrong Time-Travel" 
	,"X Must Not Win" 
	,"Yellow Brick Road" 
	,"You Already Changed The Past" 
	,"You Are Grounded" 
	,"You Can Keep Her" 
	,"You Go, Girl!" 
	,"You Have Waited Long Enough" 
	,"You Know What You Did" 
	,"You Wake Up in a Room" 
	,"You Would Make a Great Model" 
	,"Your Cheating Heart" 
	,"Your Worst Nightmare" 
	,"Zany Scheme" 
]

function getRandomTrope() {
	var trope = getRandomElement(tropes);
	return trope;
}
